### ISSUE TITLE
gene IDs - database support

### ISSUE THREAD

**Issue by paularstrpo** [r-bioinformatics/edgePy#11]
Objective: Create list of public databases containing gene ID's for gene mapping to ensure standardization && implement support for mapping these IDs into the GE (gene expression) matrices.

This will help enforce standardization in biology (at least in this package).

Description:
- implement support for these databases (i.e., entrez, refseq, etc)
- supported databases should be publicly accessible, open source, etc.
- supported databases should preferrably have manual curation if possible
- have multiple databases to cover some of the most widely used model organisms (human, mouse, etc etc)
- implement option for the event that someone is using a species for which little to no sequencing databases with genes exist

**Comment by sdhutchins** [comment]
Could look into [mygene](https://github.com/biothings/mygene.py).

They use the below annotation data. Their api is pretty easy. They're switching to their [biothings](https://github.com/biothings/biothings_client.py) api client which encompasses their variant and taxonomy apis.

![image](https://user-images.githubusercontent.com/20976111/40453107-c419346a-5ea9-11e8-846d-ed815a07b2b4.png)

**Comment by sdhutchins** [comment]
It also may be useful to take a look at http://biogps.org/ which encompasses a number of the major gene databases. They have an [API](http://biogps.org/api/).

**Comment by apfejes** [comment]
We discussed this online - I proposed that we use the Ensembl database, as they maintain IDs, and have mappings to RefseqIDs, and other systems, and are maintained frequently.  Also doens't require us to host a database anywhere, as we can use the publicly available db's.

**Comment by sdhutchins** [comment]
@apfejes Awesome! Wasn't sure if you guys talked about it or how expansive you wanted to be with databases. I'd love to help out in that regard (I know you have a strong background with working with Ensembl as well).

**Comment by paularstrpo** [comment]
I'm closing this issue since we had decided to stick with Ensembl during last week's meeting.
