### ISSUE TITLE
Pathway Analysis

### ISSUE THREAD

**Issue by eegk** [r-bioinformatics/edgePy#12]
- GO pathways 
- KEGG pathways

From this Functions in R:
goana(de, geneid = rownames(de), FDR = 0.05, trend = FALSE, ...)
kegga(de, geneid = rownames(de), FDR = 0.05, trend = FALSE, ...)

**Comment by paularstrpo** [comment]
Pathway analysis is a workflow of its own. I think it is worth working on, however the goal right now in this repository is to implement the differential gene expression (DGE) analysis workflow. This is something that is better addressed in a separate repo at a later time.

**Comment by eegk** [comment]
it is within edgeR package. its not  diff. repo.

**Comment by paularstrpo** [comment]
I thought we agreed to collapse different packages from bioconductor so that we port analysis workflow by analysis workflow; not necessarily package by package. This, to me at least, seems to be a more efficient way to organize our code.

**Comment by eegk** [comment]
well, everyone agrees its ok. but those are really simple functions to implement and most of DE analysis ends there so I thought it could be important to check.

**Comment by paularstrpo** [comment]
This should be debated further in the slack and/or next meeting since organizing the repo workflow by workflow instead of package by package could necessitate changes to the repo name, as well as the documentation. I'm leaving this issue open for now to facilitate discussion on the topic.
