### ISSUE TITLE
Should we use a more permissive open source license?

### ISSUE THREAD

**Issue by clintval** [r-bioinformatics/edgePy#20]
I understand that the `edgeR` R package is licensed under GPL>=2.

I personally favor a more permissive license for scientific software, the MIT License.

Comment here for discussion on which license this port should adopt.

**Comment by clintval** [comment]
@apfejes you committed the GPL to this repo so pinging you in.

**Comment by apfejes** [comment]
I agree - please switch to MIT.

**Comment by clintval** [comment]
Closed with #21
