### ISSUE TITLE
Implementation of method `cpm()` and corresponding tests

### ISSUE THREAD

**Issue by clintval** [r-bioinformatics/edgePy#23]
I wrote pseudo-code but I am not sure if it is correct!

https://github.com/r-bioinformatics/edgePy/blob/cbb5eeb1a0c15a57e4d3583d6d250ee37161543c/edgePy/_DGEList.py#L181-L192

This method is a dependency for all other normalization procedure so it would be great to have this flushed out and tested!

**Comment by clintval** [comment]
I would rather prefer the argument `to_log_transform` over `log` which indicates the option is a boolean choice and that the action is a transformation.

**Comment by julianstanley** [comment]
This looks good to me, at least. 

In case it's useful or you don't know, here's edgeR's implementation of CPM for non-log values. I can't read C well, but it looks just like an optimized version of basically just  ![image](https://user-images.githubusercontent.com/22749289/42600041-09a66e16-852f-11e8-85ef-c4a6a06cecd0.png)


```
SEXP calculate_cpm_raw (SEXP y, SEXP libsize) {
    BEGIN_RCPP

    // Checking the inputs.
    any_numeric_matrix input(y);
    const int num_tags=input.get_nrow();
    const int num_libs=input.get_ncol();

    Rcpp::NumericMatrix outmat(num_tags, num_libs);
    if (input.is_data_integer()) { 
        auto tmp=input.get_raw_int();
        std::copy(tmp.begin(), tmp.end(), outmat.begin());
    } else {
        auto tmp=input.get_raw_dbl();
        std::copy(tmp.begin(), tmp.end(), outmat.begin());
    }

    compressed_matrix allL(libsize);
    if (allL.get_nrow()!=num_tags || allL.get_ncol()!=num_libs) {
        throw std::runtime_error("dimensions are not consistent between counts and library sizes");
    }

    // Doing the various calculations.
    for (int tag=0; tag<num_tags; ++tag) {
        auto current_row=outmat.row(tag);
        const double* lptr=allL.get_row(tag);

        for (auto& curval : current_row) { 
            if ((*lptr)>0) {
                curval*=one_million/(*lptr);
            } else {
                curval=R_NaN;
            }
            ++lptr;
        }
    }

    return outmat;
    END_RCPP
}


```

**Comment by clintval** [comment]
@apfejes check out this thread which was reserved for implementation of the `self.cpm()` method.

**Comment by apfejes** [comment]
Thanks @clintval.

That's very helpful!

**Comment by apfejes** [comment]
This has already been merged.
