### ISSUE TITLE
Nitpick: setting the wrong type should be a TypeError

### ISSUE THREAD

**Issue by clintval** [r-bioinformatics/edgePy#25]
https://github.com/r-bioinformatics/edgePy/blob/cbb5eeb1a0c15a57e4d3583d6d250ee37161543c/edgePy/_DGEList.py#L102

**Comment by vzg100** [comment]
All take a stab at this to better learn GitHub!

**Comment by clintval** [comment]
Perfect! I've assigned you. Ping me if you need anything or have questions. Also if a part of our `CONTRIBUTING.md` needs better language feel free to suggest or edit in your Pull Request.
