### ISSUE TITLE
Reorganization to keep the root of this project cleaner

### ISSUE THREAD

**Issue by clintval** [r-bioinformatics/edgePy#28]
- [ ] ~Move `tests` to `edgePy/tests` so they are packaged with install~
   - [ ] ~Adjust test runners~
- [x] Delete directory `libs/` and [remove the submodule](https://stackoverflow.com/questions/1260748/how-do-i-remove-a-submodule) for R
- [ ] ~Add a section in `CONTRIBUTING.md` for which `edgeR` hash we are referencing:~

Command is simliar to: `git clone <edgeR repo> && git checkout 804ace8`

This will keep the project a little tidier. We will package `tests/` on install. TravsCI builds will be faster since we do not have to recursive clone `edgeR` everytime.

**Comment by TrackAddict** [comment]
I can do the cleanup tonight.

Are we even explicitly referring to edgeR anymore? As I understand it we're using bioconductor as a (very) high-level inspiration for the features we want to provide, and then implementing them ourselves without heavily emulating the R packages.
