### ISSUE TITLE
Wrong license in `setup.py`

### ISSUE THREAD

**Issue by clintval** [r-bioinformatics/edgePy#32]
Should be MIT here:

https://github.com/r-bioinformatics/edgePy/blob/1d53f92dcd94c876536e275ad723df98aa8d8b5e/setup.py#L44

And the trove classifier here:

https://github.com/r-bioinformatics/edgePy/blob/1d53f92dcd94c876536e275ad723df98aa8d8b5e/setup.py#L55

**Comment by clintval** [comment]
Here are valid trove classifiers:

https://pypi.org/pypi?%3Aaction=list_classifiers

**Comment by julianstanley** [comment]
@vzg100 Yeah, I think so. I think it's just leftover--I changed to the MIT license but I forgot to change setup.py.

I think should just be:

Line 44: license = "MIT"
Line 55: 'License :: OSI Approved :: MIT License'

Should be straightforward for anyone else wanting to practice a the pull request process

**Comment by Carbyne** [comment]
Could I try this as pull request practice?
