### ISSUE TITLE
Switch to using 119 characters per line, instead of 99.

### ISSUE THREAD

**Issue by apfejes** [r-bioinformatics/edgePy#43]
Unless you're editing in a command line environment with a limited screen width, most projects these days tend to loosen up a bit in the line width requirements.  I suggest we go to 119 characters, to make editing easier and cleaner.

**Comment by clintval** [comment]
I'm cool, can you make a PR updating our docs and corresponding lint settings?

**Comment by apfejes** [comment]
Included in PR https://github.com/r-bioinformatics/edgePy/pull/40
