### ISSUE TITLE
Add documentation for io submodule

### ISSUE THREAD

**Issue by Carbyne** [r-bioinformatics/edgePy#52]
The io submodule needs docstrings and documentation regarding which kinds of paths smart_open can handle (ex. local compressed/uncompressed files, S3/Hadoop/HTTP servers).

**Comment by apfejes** [comment]
This module is now renamed to data_import.  io is a reserved package name and shouldn't be reused.

**Comment by apfejes** [comment]
@Carbyne  - Since we're using an outside library, shouldn't we just point to the document there, so that we don't have to maintain a list?

https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst

**Comment by Carbyne** [comment]
Yeah, that would be a better solution. The only problem I could see would be if they changed something in a newer version of smart_open and we were still using an older version.

**Comment by apfejes** [comment]
That shouldn't happen, as requirements are given in the ">=" form, so any new install should bring along a new version.

**Comment by joshuak94** [comment]
Okay to close the issue?

**Comment by apfejes** [comment]
I think so.  Closing.  If anyone objects, reopen.
