### ISSUE TITLE
Make an RST table

### ISSUE THREAD

**Issue by clintval** [r-bioinformatics/edgePy#68]
This looks ugly: https://edgepy.readthedocs.io/en/latest/planned_statistical_tests.html

I suggest a simple table as format option: http://docutils.sourceforge.net/docs/user/rst/quickref.html#tables

**Comment by sdhutchins** [comment]
I'll jump on.

**Comment by sdhutchins** [comment]
I think the issue is that the conf.py isn't converting this though. I'll create a branch a test.

**Comment by clintval** [comment]
Ah, goodpoint. btw we really should use RST with Sphinx. I've had terrible luck with Markdown support and I eventually want to use `pytest --doctest-glob='*rst'` on this project.

**Comment by clintval** [comment]
Also do you know if that table could close out this issue?

https://github.com/r-bioinformatics/edgePy/issues/7

**Comment by apfejes** [comment]
I believe it does close #7.

If you agree, please close.
