### ISSUE TITLE
list of statistical tests

### ISSUE THREAD

**Issue by paularstrpo** [r-bioinformatics/edgePy#7]
Compile list of statistical tests that are used in edgeR, which are well implemented in third-party python libraries (include mapping of statistical test::library implementation). Items to cross-check (non-exhaustive):

- Exact tests
- Curve fitting
- Generalized Linear Models
- Filtering

**Comment by clintval** [comment]
- [ ] listitem1
- [ ] listitem2

**Comment by paularstrpo** [comment]
In the google drive (linked from the slack) I'm putting a spreadsheet named "statistical tests R-Python Library mapping" - we can use that for making the list

**Comment by eegk** [comment]
The document you mention in google drive @paularstrpo  cant be edited. it is set to view only.
