### ISSUE TITLE
Update tox to python 3.7

### ISSUE THREAD

**Issue by moritzschaefer** [r-bioinformatics/edgePy#74]
It's been a few months since Python received a minor version upgrade (3.7). As it is (of course) downwards compatible and it should be encouraged to use up to date software, I would suggest to use python 3.7 as default interpreter in tox.

**Comment by vghorakavi** [comment]
@moritzschaefer Are you working on this issue?  Would you be okay if I jumped in?

**Comment by vghorakavi** [comment]
@moritzschaefer Hey!  Thanks for letting me know.  Want to jump back into the project after making a small change.  I will let you continue.

**Comment by clintval** [comment]
There are backwards incompatible features in 3.7. to ensure we remain Py3.6+ you'll actually have to run testing under both Python interpreter versions. 

TravisCI can be configured with Tox to also run a matrix of interpreters.

My bid: do not drop Py3.6 testing.

**Comment by apfejes** [comment]
I agree with clintval - lets not force this move just yet.
